# webhook/k8s/webhook.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-webhook
  template:
    metadata:
      labels:
        app: gpu-webhook
    spec:
      serviceAccountName: gpu-webhook
      containers:
      - name: webhook
        image: brunolaureano/gpu-webhook:latest
        securityContext:
          privileged: true
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: gpu-webhook-certs
---
# (Segundo objeto) Service
apiVersion: v1
kind: Service
metadata:
  name: gpu-webhook                # mesmo nome que o MutatingWebhookConfiguration usa
  namespace: kube-system
spec:
  selector:
    app: gpu-webhook               # bate com o label do Deployment acima
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
