# webhook/k8s/webhook.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-webhook
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: gpu-webhook
  namespace: kube-system
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: gpu-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-webhook
  template:
    metadata:
      labels:
        app: gpu-webhook
    spec:
      serviceAccountName: gpu-webhook
      containers:
      - name: webhook
        image: brunolaureano/gpu-webhook:latest
        securityContext:
          privileged: true  # Necessário para acessar GPU e executar sudo
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
        - name: onboarding-package
          mountPath: /home/cgpu-onboarding/cgpu-onboarding-package
        - name: nvidia-utils
          mountPath: /usr/bin/nvidia-smi
        - name: gpu-drivers
          mountPath: /usr/lib/x86_64-linux-gnu
      volumes:
      - name: webhook-certs
        secret:
          secretName: gpu-webhook-certs
      - name: onboarding-package
        hostPath:
          path: /home/cgpu-onboarding/cgpu-onboarding-package
          type: Directory
      - name: nvidia-utils
        hostPath:
          path: /usr/bin/nvidia-smi
          type: File
      - name: gpu-drivers
        hostPath:
          path: /usr/lib/x86_64-linux-gnu
          type: Directory