# webhook/k8s/webhook-config.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gpu-webhook-cfg
webhooks:
  - name: gpu.webhook.k8s.io
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values: ["kube-system"]
    clientConfig:
      service:
        name: gpu-webhook
        namespace: kube-system
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5